to update openssl-3.0.2

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -8,188 +8,159 @@
 # This file may have to be extensively modified
 #
 # Modified to be a prototype for debmake by Christoph Lameter <clameter@debian.org>
+include /usr/share/dpkg/architecture.mk
+include /usr/share/dpkg/pkg-info.mk
+
+export DEB_BUILD_MAINT_OPTIONS = hardening=+all future=+lfs
+export DEB_CFLAGS_MAINT_APPEND = -DOPENSSL_TLS_SECURITY_LEVEL=2
+
 SHELL=/bin/bash
 
 package=openssl
 
 # For generating the manpages
-export VERSION=$(shell dpkg-parsechangelog | grep '^Version:' | sed -e 's/^.*://' -e 's/-.*//')
+export VERSION=$(DEB_VERSION_UPSTREAM)
 
-# The binary architeture
-DEB_HOST_ARCH = $(shell dpkg-architecture -qDEB_HOST_ARCH)
-DEB_HOST_ARCH_OS = $(shell dpkg-architecture -qDEB_HOST_ARCH_OS)
-
-DEB_HOST_MULTIARCH=$(shell dpkg-architecture -qDEB_HOST_MULTIARCH)
-DEB_HOST_ARCH_CPU=$(shell dpkg-architecture -qDEB_HOST_ARCH_CPU)
-
-DEB_HOST_GNU_TYPE=$(shell dpkg-architecture -qDEB_HOST_GNU_TYPE)
-DEB_BUILD_GNU_TYPE=$(shell dpkg-architecture -qDEB_BUILD_GNU_TYPE)
 ifneq ($(DEB_HOST_GNU_TYPE),$(DEB_BUILD_GNU_TYPE))
-CROSS=CC=$(DEB_HOST_GNU_TYPE)-gcc
-MAKE_TEST=:
-else
-CROSS=CC=$(CC)
-MAKE_TEST=make test
+	export CROSS_COMPILE ?= $(DEB_HOST_GNU_TYPE)-
 endif
 
-ifeq ($(DEB_HOST_ARCH),amd64)
- ARCH_CONFARGS := enable-ec_nistp_64_gcc_128
+ifneq (,$(filter parallel=%,$(DEB_BUILD_OPTIONS)))
+	NUMJOBS = $(patsubst parallel=%,%,$(filter parallel=%,$(DEB_BUILD_OPTIONS)))
+	MAKEFLAGS += -j$(NUMJOBS)
 endif
-CONFARGS  = --prefix=/usr --openssldir=/usr/lib/ssl --libdir=lib/$(DEB_HOST_MULTIARCH) no-idea no-mdc2 no-rc5 no-zlib  enable-tlsext no-ssl2 $(ARCH_CONFARGS)
+
+CONFARGS  = --prefix=/usr --openssldir=/usr/lib/ssl --libdir=lib/$(DEB_HOST_MULTIARCH) no-idea no-mdc2 no-rc5 no-zlib no-ssl3 enable-unit-test no-ssl3-method enable-rfc3779 enable-cms no-capieng
 OPT_alpha = ev4 ev5
 ARCHOPTS  = OPT_$(DEB_HOST_ARCH)
 OPTS      = $($(ARCHOPTS))
-WANTED_LIBC_VERSION = 2.3.1-10
+
+ifeq (,$(findstring terse,$(DEB_BUILD_OPTIONS)))
+	TESTSUITE_FLAGS = HARNESS_VERBOSE=yes
+else
+	TESTSUITE_FLAGS =
+endif
 
 ifeq ($(DEB_HOST_ARCH_CPU), amd64)
 	CONFARGS += enable-ec_nistp_64_gcc_128
 endif
 
-ifneq (,$(findstring nocheck,$(DEB_BUILD_OPTIONS)))
-	MAKE_TEST = :
-endif
+%:
+	dh $@ --without autoreconf
 
-build: build-arch build-indep
-build-arch: build-stamp
-build-indep: build-stamp
-build-stamp:
-	dh_testdir
-#	perl util/ssldir.pl /usr/lib/ssl
-#	chmod +x debian/libtool
-	./Configure no-shared $(CONFARGS) debian-$(DEB_HOST_ARCH)
-	$(if $(filter enable-ec_nistp_64_gcc_128, $(CONFARGS)), make $(CROSS) -f Makefile depend)
-	make $(CROSS) -f Makefile all
-	$(MAKE_TEST)
-	mv libcrypto.a libcrypto.static
-	mv libssl.a libssl.static
-	make -f Makefile clean
+override_dh_auto_configure:
 	test -z "$(OPTS)" || for opt in $(OPTS); \
 	do \
 		set -xe; \
-		./Configure shared $(CONFARGS) debian-$(DEB_HOST_ARCH)-$$opt; \
-		make $(CROSS) -f Makefile all; \
-		$(MAKE_TEST); \
-		mkdir -p $$opt; \
-		mv libcrypto.so* libssl.so* $$opt/; \
-		make -f Makefile clean; \
+		mkdir build_$$opt; \
+		cd build_$$opt ; \
+		../Configure shared $(CONFARGS) debian-$(DEB_HOST_ARCH)-$$opt; \
+		perl configdata.pm -d; \
+		cd .. ;\
 	done
-	./Configure shared $(CONFARGS) debian-$(DEB_HOST_ARCH)
-	#make $(CROSS) -f Makefile depend
+	mkdir build_static; cd build_static; ../Configure no-shared $(CONFARGS) debian-$(DEB_HOST_ARCH) ;perl configdata.pm -d
+	# Debian Perl policy 5.1 (Script Magic)
+	mkdir build_shared; cd build_shared; HASHBANGPERL=/usr/bin/perl ../Configure shared $(CONFARGS) debian-$(DEB_HOST_ARCH) ;perl configdata.pm -d
+
+override_dh_auto_build-indep:
+	$(MAKE) -C build_shared all
+
+override_dh_auto_build-arch:
+	$(MAKE) -C build_static all
+	test -z "$(OPTS)" || for opt in $(OPTS); \
+	do \
+		set -xe; \
+		$(MAKE) -C build_$$opt all; \
+	done
 	ln -sf apps/openssl.pod crypto/crypto.pod ssl/ssl.pod doc/
-#	make $(CROSS) -f Makefile linux-shared
-	make $(CROSS) -f Makefile all
-	$(MAKE_TEST)
-#	strip apps/openssl
-#	make -f Makefile clean
-#	./Configure --prefix=/usr --openssldir=/usr/lib/ssl no-idea no-mdc2 no-rc5 debian-$(DEB_HOST_ARCH)
-#	make $(CROSS) -f Makefile all
-	touch build-stamp
+	$(MAKE) -C build_shared all
 
-clean:
-	dh_testdir
-	dh_testroot
-	-rm -f build-stamp
-	-./Configure $(CONFARGS) debian-$(DEB_HOST_ARCH)
-	-sed -i -e 's/rm -f/rm -rf/' Makefile
-	[ ! -f Makefile ] || make -f Makefile  clean clean-shared
-	#-make -f Makefile  dclean
-#	perl util/ssldir.pl /usr/local/ssl
-	-rm -f test/.rnd test/testkey.pem test/testreq.pem test/certCA.srl
-	-rm -f util/mk1mf.bak Makefile.bak `find . -name Makefile.save` 
-	-rm -f crypto/pem/ctx_size
-	-rm -f `find . -name "*~"`
-	-rm -f `find . -name "*.orig" -o -name "*.rej"`
-	-rm -f certs/*.0 certs/*.1
-#	-rm -rf debian/tmp debian/files* core `find debian/* -type d`
-	-rm -rf core $(OPTS)
-	-rm doc/*.pod
-	-rm -f libcrypto.* libssl.*
-	-cd test && rm -f .rnd tmp.bntest tmp.bctest *.o *.obj lib tags core .pure .nfs* *.old *.bak fluff bntest ectest  ecdsatest ecdhtest ideatest md2test  md4test md5test hmactest rc2test rc4test rc5test destest shatest sha1test sha256t sha512t mdc2test rmdtest randtest dhtest enginetest bftest casttest ssltest exptest dsatest rsa_test evp_test *.ss *.srl log dummytest newkey.pem igetest jpaketest srptest wp_test asn1test
-	-rm Makefile apps/CA.pl tools/c_rehash crypto/opensslconf.h crypto/x86_64cpuid.S
-	rm -f test/asn1test test/wp_test test/srptest test/jpaketest
-	rm -f certs/demo/*.0
-	rm -rf crypto/aes/aes-armv4.S crypto/bn/armv4-gf2m.S crypto/modes/ghash-armv4.S crypto/sha/*.S
-	dh_clean
+override_dh_auto_test-indep:
 
-install: build
-	dh_testdir
-	dh_testroot
-	dh_clean
+override_dh_auto_test-arch:
+ifneq (,$(findstring nocheck,$(DEB_BUILD_OPTIONS)))
+	@echo Skipping tests
+else
+	test -z "$(OPTS)" || for opt in $(OPTS); \
+	do \
+		set -xe; \
+		$(MAKE) -C build_$$opt test $(TESTSUITE_FLAGS); \
+	done
+	$(MAKE) -C build_static test $(TESTSUITE_FLAGS)
+	$(MAKE) -C build_shared test $(TESTSUITE_FLAGS)
+endif
+
+override_dh_auto_clean:
+	rm -rf build_static build_shared
+	test -z "$(OPTS)" || for opt in $(OPTS); \
+	do \
+		set -xe; \
+		rm -rf build_$$opt; \
+	done
+	rm -f doc/openssl.pod doc/crypto.pod doc/ssl.pod
+	dh_auto_clean
+
+override_dh_auto_install-indep:
+	# Install is only required for the -indep only build, that is if
+	# -arch isn't run as well. Otherwise install will fail because
+	# usr/lib/ssl/cert is a symlink to a non existing target.
+	if [ ! -L debian/tmp/usr/lib/ssl/certs ]; then \
+		$(MAKE) -C build_shared install DESTDIR=`pwd`/debian/tmp ;\
+		mkdir -p debian/tmp/usr/include/$(DEB_HOST_MULTIARCH)/openssl ;\
+		mv debian/tmp/usr/include/openssl/opensslconf.h debian/tmp/usr/include/$(DEB_HOST_MULTIARCH)/openssl/ ;\
+		mv debian/tmp/usr/include/openssl/configuration.h debian/tmp/usr/include/$(DEB_HOST_MULTIARCH)/openssl/ ;\
+	fi
+
+override_dh_auto_install-arch:
+	# We need the -udeb directories now!
 	dh_installdirs
-	make -f Makefile $(CROSS) install INSTALL_PREFIX=`pwd`/debian/tmp
-
-binary-indep:	build install
-	dh_testdir
-	dh_testroot
-	dh_installdirs -i
-	dh_installman -plibssl-doc
-	dh_installdocs -i
-	dh_movefiles -i
-	dh_installchangelogs -i CHANGES
-	dh_compress -i
-	dh_fixperms -i
-	dh_gencontrol -i
-	dh_installdeb -i
-	dh_md5sums -i
-	dh_builddeb -i
-
-binary-arch:	build install
-	dh_testdir
-	dh_testroot
-	dh_installdirs -a
+	$(MAKE) -C build_shared install DESTDIR=`pwd`/debian/tmp
 	# pic static libraries, nobody should need them
-#	mv debian/tmp/usr/lib/libcrypto.a debian/tmp/usr/lib/libcrypto_pic.a
-#	mv debian/tmp/usr/lib/libssl.a debian/tmp/usr/lib/libssl_pic.a
-	cp -pf libcrypto.static debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/libcrypto.a
-	cp -pf libssl.static debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/libssl.a
-	# move runtime libraries to /lib
-	install -d debian/tmp/lib/$(DEB_HOST_MULTIARCH)
-	mv debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/lib*.so.* debian/tmp/lib/$(DEB_HOST_MULTIARCH)
-	ln -sf /lib/$(DEB_HOST_MULTIARCH)/$$(readlink debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/libcrypto.so) debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/libcrypto.so
-	ln -sf /lib/$(DEB_HOST_MULTIARCH)/$$(readlink debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/libssl.so) debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/libssl.so
+	cp -pf build_static/libcrypto.a debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/libcrypto.a
+	cp -pf build_static/libssl.a debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/libssl.a
 	mkdir -p debian/tmp/etc/ssl
 	mv debian/tmp/usr/lib/ssl/{certs,openssl.cnf,private} debian/tmp/etc/ssl/
 	ln -s /etc/ssl/{certs,openssl.cnf,private} debian/tmp/usr/lib/ssl/
-	cp -pf debian/tmp/lib/$(DEB_HOST_MULTIARCH)/libcrypto.so.* debian/libcrypto1.0.0-udeb/lib/
-	cp -pf debian/tmp/lib/$(DEB_HOST_MULTIARCH)/libssl.so.* debian/libssl1.0.0-udeb/lib/
-	for opt in $(OPTS); do set -xe; mkdir -p debian/tmp/lib/$(DEB_HOST_MULTIARCH)/$$opt; cp -auv $$opt/lib*.so* debian/tmp/lib/$(DEB_HOST_MULTIARCH)/$$opt/; done
+ifeq (,$(filter noudeb,$(DEB_BUILD_PROFILES)))
+	cp -pf debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/libcrypto.so.* debian/libcrypto3-udeb/usr/lib/
+	cp -pf debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/ossl-modules/*.so debian/libcrypto3-udeb/usr/lib/ossl-modules
+	cp -pf debian/tmp/etc/ssl/openssl.cnf debian/libcrypto3-udeb/usr/lib/ssl/openssl.cnf
+	cp -pf debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/libssl.so.* debian/libssl3-udeb/usr/lib/
+endif
+	cp -auv build_shared/lib*.so* debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/
+	for opt in $(OPTS); \
+		do set -xe; \
+		mkdir -p debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/$$opt; \
+		cp -auv build_$$opt/lib*.so* debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)/$$opt/; \
+	done
 	mkdir -p debian/tmp/usr/include/$(DEB_HOST_MULTIARCH)/openssl
 	mv debian/tmp/usr/include/openssl/opensslconf.h debian/tmp/usr/include/$(DEB_HOST_MULTIARCH)/openssl/
-	install debian/copyright debian/libssl1.0.0/usr/share/doc/libssl1.0.0/
-	install debian/changelog debian/libssl1.0.0/usr/share/doc/libssl1.0.0/changelog.Debian
-	install debian/copyright debian/libssl-dev/usr/share/doc/libssl-dev/
-	install debian/changelog debian/libssl-dev/usr/share/doc/libssl-dev/changelog.Debian
+	mv debian/tmp/usr/include/openssl/configuration.h debian/tmp/usr/include/$(DEB_HOST_MULTIARCH)/openssl/
 
-	dh_installdocs -a CHANGES.SSLeay README NEWS debian/README.optimization
-	dh_installexamples -a
-	dh_installchangelogs -a CHANGES
-	dh_installman -popenssl
-	dh_installdebconf -a
-	dh_movefiles -a
-	dh_compress -a
-# symlink doc files
+override_dh_installchangelogs:
+	dh_installchangelogs CHANGES.md
+
+override_dh_fixperms:
+	if [ -d debian/openssl/etc/ssl/private ] ; then \
+		chmod 700 debian/openssl/etc/ssl/private ; \
+	fi
+	dh_fixperms -a -X etc/ssl/private
+
+override_dh_compress:
+	dh_compress
+	# symlink doc files
 	for p in openssl libssl-dev; do \
 	  for f in changelog.Debian.gz changelog.gz copyright; do \
-	    ln -sf ../libssl1.0.0/$$f debian/$$p/usr/share/doc/$$p/$$f; \
+	    ln -sf ../libssl3/$$f debian/$$p/usr/share/doc/$$p/$$f; \
 	  done; \
 	done
-	chmod 700 debian/openssl/etc/ssl/private
-	dh_fixperms -a -X etc/ssl/private
-	dh_strip -plibssl1.0.0 --dbg-package=libssl1.0.0-dbg
-	dh_strip -a -Nlibssl1.0.0
-	dh_perl -a -d
-	dpkg-gensymbols -Pdebian/libssl1.0.0/ -plibssl1.0.0 -c4
-	dh_makeshlibs -a -V "libssl1.0.0 (>= 1.0.1d)" --add-udeb="libcrypto1.0.0-udeb" -Xengines
-	sed -i '/^udeb: libssl/s/libcrypto1.0.0-udeb/libssl1.0.0-udeb/' debian/libssl1.0.0/DEBIAN/shlibs
-	dh_shlibdeps -a -L libssl1.0.0 -l debian/libssl1.0.0/lib/$(DEB_HOST_MULTIARCH)
-	dh_gencontrol -a
-	dh_installdeb -a
-	dh_md5sums -a
-	dh_builddeb -a
-	echo -en "\a"
 
-# Below here is fairly generic really
+override_dh_perl:
+	dh_perl -d
 
-binary:		binary-indep binary-arch
+override_dh_makeshlibs:
+	dh_makeshlibs -a -V --add-udeb="libcrypto3-udeb" -Xengines -Xossl-modules -- -c4
 
-.PHONY: binary binary-arch binary-indep clean install
+override_dh_shlibdeps:
+	sed -i '/^udeb: libssl/s/libcrypto3-udeb/libssl3-udeb/' debian/libssl3/DEBIAN/shlibs
+	dh_shlibdeps -a -L libssl3
